#!/bin/bash

echo "🔧 Invoke Accessibility 权限诊断工具"
echo "=================================="
echo ""

echo "🔍 检查当前状态："
echo "----------------"

# 检查 Accessibility 权限
PROCESS_TRUSTED=$(osascript -e 'tell application "System Events" to return (get accessibility enabled of (first process whose name is "Invoke"))')
if [ "$PROCESS_TRUSTED" = "true" ]; then
    echo "✅ Invoke 具有 Accessibility 权限"
else
    echo "❌ Invoke 缺少 Accessibility 权限"
fi

echo ""
echo "📱 Pair 按钮测试步骤："
echo "--------------------"
echo "1. 打开浏览器，访问 Gemini AI"
echo "2. 在 Invoke 中点击 'Pair' 按钮"
echo "3. 如果弹出权限提示窗口："
echo ""
echo "⚠️  重要权限设置指南："
echo "======================"
echo ""
echo "如果看到权限提示窗口，请按以下步骤操作："
echo ""
echo "1️⃣ 点击 '打开设置' 按钮"
echo "   → 自动打开 System Preferences"
echo ""
echo "2️⃣ 在 Accessibility 列表中："
echo "   ✅ 查找所有 'Invoke' 条目"
echo "   ❌ 删除旧的/重复的 Invoke 条目"
echo "   ✅ 只保留最新的一个 Invoke"
echo "   ✅ 确保该条目被勾选 ☑️"
echo ""
echo "3️⃣ 关闭 System Preferences"
echo ""
echo "4️⃣ 重新测试 Pair 功能："
echo "   → 应该看到窗口最小化"
echo "   → 浏览器获得焦点"
echo "   → 协议文本自动插入"
echo "   → 窗口自动恢复"
echo ""

echo "🚨 故障排除："
echo "============"
echo ""
echo "如果仍然无法自动粘贴："
echo ""
echo "原因可能："
echo "• Accessibility 列表中有多个 Invoke 条目冲突"
echo "• 权限未正确授予最新的 Invoke 版本"
echo "• 需要重启 Invoke 应用"
echo ""
echo "解决方案："
echo "1. 完全退出 Invoke (Cmd+Q)"
echo "2. 打开 System Preferences > Security & Privacy > Accessibility"
echo "3. 删除所有 Invoke 相关条目"
echo "4. 重新启动 Invoke"
echo "5. 点击 Pair 按钮触发新的权限请求"
echo "6. 授予权限后重试"
echo ""

echo "🎯 快速重置权限："
echo "================"
echo ""
echo "# 完全重置 Accessibility 权限"
echo "sudo tccutil reset Accessibility com.yukungao.invoke"
echo ""
echo "# 重启 Invoke 并触发新权限请求"
echo "pkill Invoke && open Invoke.app"
echo ""

echo "✅ 修复要点总结："
echo "================"
echo ""
echo "🔑 现在 Pair 按钮会："
echo "• 检查 Accessibility 权限"
echo "• 权限不足时弹出详细说明窗口"
echo "• 提醒删除重复条目避免冲突"
echo "• 自动打开系统设置"
echo ""
echo "🎯 测试 Pair 按钮，应该看到智能权限提示！"